# Generated by Django 4.2.5 on 2024-04-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_positions_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, default='Должность не выбрана', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.positions', verbose_name='Должность'),
        ),
    ]
