# Generated by Django 4.2.5 on 2024-04-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subdivisions', '0006_alter_subdivisions_abbreviation_and_more'),
        ('users', '0005_alter_user_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subdivision',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Subdivisions.subdivisions', verbose_name='Подразделение'),
        ),
    ]
