# Generated by Django 4.2.5 on 2024-04-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'permissions': [('users.position_add', 'Добавление должностей'), ('users.position_change', 'Изменение должностей'), ('users.position_delete', 'Удаление должностей'), ('users.position_id', 'Просмотр должности'), ('users.position_all', 'Просмотр всех должностей в таблице')], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('users.user_id', 'Просмотр пользователей'), ('users.user_delete', 'Удаление пользователей'), ('users.user_all', 'Просмотр всех пользователей в таблице')], 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
