# Generated by Django 4.2.5 on 2024-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRIT', '0002_delete_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='Характеристика инцидента')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет инцидента')),
            ],
            options={
                'verbose_name': 'Спецификация инцидентов',
                'verbose_name_plural': 'Спецификации инцидентов',
            },
        ),
    ]
