# Generated by Django 4.2.5 on 2024-04-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRIT', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
