# Generated by Django 4.2.5 on 2024-04-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRIT', '0006_delete_specificationssss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
