# Generated by Django 4.2.5 on 2024-04-19 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='Характеристика инцидента')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет инцидента')),
            ],
            options={
                'verbose_name': 'Спецификация инцидентов',
                'verbose_name_plural': 'Спецификации инцидентов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус происшествия')),
                ('description', models.CharField(max_length=100, verbose_name='Описание статуса происшествия')),
            ],
            options={
                'verbose_name': 'Статус происшествия',
                'verbose_name_plural': 'Статусы происшествий',
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('time_create',models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 19, 14, 22, 56, 794731),verbose_name='Дата и время обнаружения происшествия')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('taken_measures', models.CharField(blank=True, max_length=255, null=True, verbose_name='Принятые меры по ликвидации')),
                ('specification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Incidents.specifications', verbose_name='Спецификация происшествия')),
                ('user_create', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_create', to=settings.AUTH_USER_MODEL, verbose_name='Обнаружитель происшествия')),
                ('user_responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за происшествие')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
    ]
