# Generated by Django 4.2.5 on 2024-04-18 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='Характеристика инцидента')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет инцидента')),
            ],
            options={
                'verbose_name': 'Спецификация инцидентов',
                'verbose_name_plural': 'Спецификации инцидентов',
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('time_create', models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 19, 42, 19, 283830), verbose_name='Дата и время обнаружения происшествия')),
                ('specification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Incidents.specifications', verbose_name='Спецификация происшествия')),
                ('user_create', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Обнаружитель происшествия')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
    ]
