# Generated by Django 4.2.5 on 2024-04-19 07:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='user_responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за происшествие'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 19, 10, 19, 11, 953056), verbose_name='Дата и время обнаружения происшествия'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='user_create',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_create', to=settings.AUTH_USER_MODEL, verbose_name='Обнаружитель происшествия'),
        ),
    ]
