# Generated by Django 4.2.5 on 2023-10-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidents',
            options={'verbose_name': 'инцидент', 'verbose_name_plural': 'Инциденты'},
        ),
    ]
