# Generated by Django 4.2.5 on 2023-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0002_alter_incidents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
