# Generated by Django 4.2.5 on 2024-04-19 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0002_incidents_user_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='taken_measures',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Принятые меры по ликвидыции'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 19, 11, 0, 56, 528983), verbose_name='Дата и время обнаружения происшествия'),
        ),
    ]
