# Generated by Django 4.2.5 on 2024-04-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0004_incidents_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='pattern',
        ),
    ]
