# Generated by Django 4.2.5 on 2024-04-20 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0006_alter_incidents_status_alter_incidents_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidents',
            options={'verbose_name': 'Происшествие', 'verbose_name_plural': 'Происшествия'},
        ),
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name': 'Спецификацию происшествия', 'verbose_name_plural': 'Спецификации происшествий'},
        ),
        migrations.AddField(
            model_name='incidents',
            name='time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 17, 39, 43, 799274), null=True, verbose_name='Дата и время ликвидирования происшествия'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='time_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 17, 39, 43, 799274), null=True, verbose_name='Дата и время принятия решения'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 17, 39, 43, 799274), verbose_name='Дата и время обнаружения происшествия'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет происшествия'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='pattern',
            field=models.CharField(max_length=100, verbose_name='Характеристика происшествия'),
        ),
    ]
