# Generated by Django 4.2.5 on 2024-04-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0006_specification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specification',
            new_name='Specifications',
        ),
    ]
