# Generated by Django 4.2.5 on 2024-04-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0007_rename_specification_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Incidents.specifications'),
        ),
    ]
