# Generated by Django 4.2.5 on 2024-04-20 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0008_alter_incidents_time_create_alter_incidents_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 18, 6, 55, 157987), verbose_name='Дата и время обнаружения происшествия'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_end',
            field=models.DateTimeField(null=True, verbose_name='Дата и время ликвидирования происшествия'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_start',
            field=models.DateTimeField(null=True, verbose_name='Дата и время принятия решения'),
        ),
    ]
