# Generated by Django 4.2.5 on 2024-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0009_incidents_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
    ]
