# Generated by Django 4.2.5 on 2024-04-20 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0009_alter_incidents_time_create_alter_incidents_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 19, 46, 54, 791871), verbose_name='Дата и время обнаружения происшествия'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время ликвидирования происшествия'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время принятия решения'),
        ),
    ]
