# Generated by Django 4.2.5 on 2024-04-20 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0010_incidents_complete_alter_incidents_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 20, 3, 17, 378168), verbose_name='Дата и время обнаружения происшествия'),
        ),
    ]
