# Generated by Django 4.2.5 on 2024-04-16 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0012_alter_incidents_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 16, 16, 4, 29, 989219), verbose_name='Время обнаружения происшествия'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Incidents.specifications', verbose_name='Спецификация происшествия'),
        ),
    ]
