# Generated by Django 4.2.5 on 2024-04-20 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0012_alter_incidents_complete_alter_incidents_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidents',
            options={'permissions': [('incidents_add', 'Добавление происшествий'), ('incidents_change', 'Изменение происшествий'), ('incidents_delete', 'Удаление происшествий'), ('incidents_id', 'Просмотр происшествия'), ('incidents_map', 'Просмотр всех происшествий на карте'), ('incidents_all', 'Просмотр всех происшествий в таблице')], 'verbose_name': 'Происшествие', 'verbose_name_plural': 'Происшествия'},
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 21, 0, 36, 24, 320178), verbose_name='Дата и время обнаружения происшествия'),
        ),
    ]
