# Generated by Django 4.2.5 on 2024-04-16 16:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Incidents', '0013_incidents_time_create_alter_incidents_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='user_create',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Обнаружитель происшествия'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 16, 19, 2, 30, 395214), verbose_name='Дата и время обнаружения происшествия'),
        ),
    ]
