# Generated by Django 4.2.5 on 2024-04-20 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0013_alter_incidents_options_alter_incidents_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specifications',
            options={'permissions': [('specification_add', 'Добавление спецификации происшествия'), ('specification_change', 'Изменение спецификации происшествия'), ('specification_delete', 'Удаление спецификации происшествия'), ('specification_id', 'Просмотр спецификации происшествия'), ('specification_all', 'Просмотр всех спецификаций в таблице')], 'verbose_name': 'Спецификацию происшествия', 'verbose_name_plural': 'Спецификации происшествий'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'permissions': [('status_add', 'Добавление статуса происшествия'), ('status_change', 'Изменение статуса происшествия'), ('status_delete', 'Удаление статуса происшествия'), ('status_id', 'Просмотр статуса происшествия'), ('status_all', 'Просмотр всех статусов в таблице')], 'verbose_name': 'Статус происшествия', 'verbose_name_plural': 'Статусы происшествий'},
        ),
        migrations.AlterField(
            model_name='incidents',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 21, 0, 40, 51, 681186), verbose_name='Дата и время обнаружения происшествия'),
        ),
    ]
