# Generated by Django 4.2.5 on 2024-04-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subdivisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Subdivisions',
            name='abbreviation1',
            field=models.CharField(default='123', max_length=10, verbose_name='Aббревиатура'),
        ),
        migrations.AlterField(
            model_name='Subdivisions',
            name='abbreviation',
            field=models.CharField(default='123', max_length=10, verbose_name='Aббревиатура'),
        ),
    ]
