# Generated by Django 4.2.5 on 2024-04-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subdivisions', '0002_subdivisions_abbreviation1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Subdivisions',
            name='abbreviation1',
        ),
    ]
