# Generated by Django 4.2.5 on 2024-04-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subdivisions', '0003_remove_subdivisions_abbreviation1'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivisions',
            name='address',
            field=models.CharField(default='г. Москва', max_length=50, verbose_name='Адрес подразделения'),
        ),
    ]
