# Generated by Django 4.2.5 on 2024-04-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subdivisions', '0005_subdivisions_latitude_subdivisions_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivisions',
            name='abbreviation',
            field=models.CharField(max_length=10, verbose_name='Aббревиатура'),
        ),
        migrations.AlterField(
            model_name='subdivisions',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес подразделения'),
        ),
        migrations.AlterField(
            model_name='subdivisions',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='subdivisions',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
